apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  replicas: 1  # 단일 노드 환경에 맞게 조정
  selector:
    matchLabels:
      name: minio-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: minio-operator
        app.kubernetes.io/name: operator
        name: minio-operator
    spec:
      serviceAccountName: minio-operator
      containers:
      - name: minio-operator
        image: minio/operator:v7.1.1
        args:
        - controller
        env:
        - name: MINIO_CONSOLE_TLS_ENABLE
          value: "off"
        - name: OPERATOR_STS_ENABLED
          value: "on"
        # 추가 환경 변수 예시
        - name: MINIO_OPERATOR_RUNTIME
          value: "kubernetes"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 500Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      # 단일 노드 환경에서는 Anti-Affinity 제거
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: name
      #           operator: In
      #           values:
      #           - minio-operator
      #       topologyKey: kubernetes.io/hostname
