apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    # MinIO 최적화 어노테이션
    minio.min.io/optimized: "true"
    minio.min.io/storage-type: "local-attached"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false
parameters:
  # 로컬 스토리지 최적화 파라미터
  fsType: "ext4"
---
# Worker 노드별 Local Persistent Volume 생성
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv-worker-1
  labels:
    minio.min.io/node: "worker"
    minio.min.io/disk: "disk1"
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-data/disk1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv-worker-2
  labels:
    minio.min.io/node: "worker"
    minio.min.io/disk: "disk2"
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-data/disk2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv-worker2-1
  labels:
    minio.min.io/node: "worker2"
    minio.min.io/disk: "disk1"
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-data/disk1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv-worker2-2
  labels:
    minio.min.io/node: "worker2"
    minio.min.io/disk: "disk2"
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-data/disk2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2
